### ISSUE TITLE
UC210_che innesta 204_Richiedenti_I

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#13]
![Screenshot 2024-11-19 184150](https://github.com/user-attachments/assets/356cd613-602c-4437-b268-909ed464a9f1)
Perchè non carica il mio nome ed il mio cognome ma solo il codice fiscale?

**Comment by e-guerriero** [comment]
Cognome e nome sono caricati, li vedi più chiari perché sono dati non modificabili

**Comment by lungarella-raffaele** [comment]
Sara, questa issue posso segnarla come risolta? Magari discutiamo con Luigi per come indicare un campo non editabile ma un attimo più leggibile

**Comment by SaraGiordano334** [comment]
si diciamo che ho avuto veramente difficoltà a leggerlo anche stamattina 
fatelo un grigio un pelo piu scuro che si legga
