### ISSUE TITLE
Uscire dal deposito come senza logout

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#14]
![Screenshot 2024-11-20 071202](https://github.com/user-attachments/assets/9fab0bef-8b35-4439-8348-053da117c003)
1. Non trovo un  modo per uscire dal deposito
2.  se clicco sul breadcrumbs" i miei depositi" mi appare pop up in inglese forse andrebbe tradotto
3.  faccio "leave" mi fa logout invece di portarmi nella user area

**Comment by lungarella-raffaele** [comment]
Hai provato a ripetere questa cosa dopo il login? Non riesco a riprodurre il bug. Potrebbe essere che la tua utenza sia scaduta mentre facevi questa cosa e ti ha buttato fuori
