### ISSUE TITLE
DEPOSITO - UI/UX - SPID - Breadcrumb e sub-header non visibili

### ISSUE THREAD

**Issue by Davide-romano** [guildenstern70/uibm-test#19]
Sistema operativo: Windows 11
Browser: Google Chrome 
Percorso:
1. Atterro nella HOME del portale
2. Clicco su "Accedi all'area personale"
3. Clicco su "Entra con SPID"
4. Atterro in pagina di LOGIN completa con possibilità di accedere con SPID
5. Verifico che la pagina sia conforme e sia possibile procedere con tutte le altre operazioni prima di accedere
6. **La sub-header e la breadcrumb scompaiono erroneamente quando l'utente atterra sulla pagina di login con SPID**

**Comportamento attuale:** La sub-header e la breadcrumb scompaiono erroneamente quando l'utente atterra sulla pagina di login con SPID
**Comportamento atteso:** La sub-header e la breadcrumb dovrebbero rimanere visibili in ogni pagina, inclusa quella di login una volta cliccato su modalità di accesso "SPID"

**NB: Aggiungo che perdendo la breadcrumb non è possibile tornare alla home in alcun modo a meno che non vengano utilizzati i pulsanti back del browser.**

![image](https://github.com/user-attachments/assets/5bcb351d-d5c1-4168-abce-b31d1d856d4f)

**Comment by Davide-romano** [comment]
Aggiungo che, come potete notare dallo screen, l'header cambia nel momento in cui atterro sulla pagina di login con spid. L'elemento header che visualizzo in questa pagina è diverso e presenta ad esempio i pulsanti social differenti, oltre presentare l'intestazione del ministero diversa e al click non funzionante (ma questo dovrebbe dipendere dal fatto che si perde la breadcrumb).

**Comment by ciro-piccolo-cic** [comment]
ciao Davide, 
per loggarsi con SPID o simili, utilizziamo un'applicativo esterno gestito da MISE. 
on abbiamo controllo su questa pagina ovviamente, quindi non possiamo gestire questa issue

**Comment by guildenstern70** [comment]
Chiudo perché non è di nostra competenza.
