### ISSUE TITLE
Simula tasse  minor

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#31]
![Screenshot 2024-11-21 080427](https://github.com/user-attachments/assets/a5db6e77-3039-41c3-b779-a7fcf542de2e)
1. Il carattere del nota bene è diverso dall'intero sito uniformarlo
2. nel nota bene sostituire "step del pagamento" con " Step riepilogo costi"

**Comment by guildenstern70** [comment]
Il carattere era così nel wireframe... non mi dispiace... puoi verificare con Luigi?

**Comment by guildenstern70** [comment]
Inoltre il font è quello anche per "Designers Italia", vedi:
https://www.figma.com/design/BkWe7ggTQoJkan3V569mMh/DEV-Protos-show-v7-on-draft-team-vv2.2?node-id=1688-143385&node-type=canvas&t=XtDYXfAbBfLvfthZ-0
