### ISSUE TITLE
!!!Simula tasse  per Brevetto NOn simula il costo 

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#32]
![Screenshot 2024-11-21 080737](https://github.com/user-attachments/assets/0153611e-901d-49c8-a026-070d67758b4b)
anche avendo inserito i dati tipo rivendicazioni oltre la decima o altro NON calcola il costo previsto per il deposito 
![Screenshot 2024-11-21 081031](https://github.com/user-attachments/assets/08bec473-18e5-44b2-a4eb-b9aa564854de)

**Comment by SaraGiordano334** [comment]
Alessio, per me non funziona ancora:
![immagine](https://github.com/user-attachments/assets/133bc25a-bd68-4142-a787-26316f484d5d)
1.per ogni rivendicazione oltre la decima deve calcolare i 45 euro
2. deve aggiungere i 200 euro della traduzione
3. se aggiungo i documenti "lettera in carico" deve in base al tipo documento moltiplicare per il costo del singolo documento aggiunto
in sintesi in questo UC si deve simulare l'algoritmo del pagamento che nn so se avete implementato xche nn ci sono ancora arrivata nei test

**Comment by guildenstern70** [comment]
A me vengono i 200 euro della traduzione se scelgo di averla. 

Comunque ecco a cosa servono i test book. Abbiamo bisogno di un test book, con i passi da seguire e gli importi attesi facendo questi passi.

<img width="697" alt="Screenshot 2024-11-21 at 16 47 10" src="https://github.com/user-attachments/assets/4106337f-a96c-4e23-b4df-86e0dfdf4a4a">

**Comment by SaraGiordano334** [comment]
Io continuo a non vedere nella simulazione:
1. il costo dei 200 euro ( forse l'errore che fai è che se seleziono il toggle rivendicazioni in inglese il costo dei 200 euro si toglie, mentre di default c'è)
2.  se aggiungo le lettere di incarico o quelle multiple non vedo il costo totale aggiunto che è  il loro costo singolo x la  quantità immessa ( nel file allegato vedi le righe 346 e 347)
[Elenco-tasse-bolli-NSara (1)(1).xls](https://github.com/user-attachments/files/17867243/Elenco-tasse-bolli-NSara.1.1.xls)

**Comment by guildenstern70** [comment]
1. Sì, era erroneamente così. Correggo.
2. Ah, OK!

Proviamo ora.
