### ISSUE TITLE
UC210 che innesta 206 documentazione

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#35]
![Screenshot 2024-11-21 144053](https://github.com/user-attachments/assets/0faf26ac-0cce-4ce5-9831-aa40a258ace5)
1. xche c'è il dowload ed elimina di un file che non ho ancora caricato?
2. ho provato a caricare un pdf e non ci sono riuscita

**Comment by lungarella-raffaele** [comment]
I pulsanti `Download` ed `Elimina` sono in uno stato disabilitato quando il file non è presente. Li nascondo?
Ne approfitto per chiedere un chiarimento sul pulsante `Download`. secondo la documentazione dovrebbe apparire solo nel momento in cui abbiamo un file convertito da DOCX, siccome convertire un file DOCX all'invio non sarà possibile dobbiamo rivedere questa feature. Per ora lo elimino? Oppure lo lasciamo?

**Comment by SaraGiordano334** [comment]
si elimina xche era una richiesta del cliente poi capiamo come farla.
si nascondi anche elimina finche nn si carica

**Comment by SaraGiordano334** [comment]
io xo li vdo ancora
