### ISSUE TITLE
UC210 che innesta 205 domiclio elettivo nazione estera non funziona avanti

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#51]
se metto nazione diversa da ITALIA 
i controlli nn sono corretti e cmq NON Mi fa andare avanti

**Comment by Dariopurpi** [comment]
ciao Sara,
ho fatto un check sia su chrome che su firefox e non risulta questo errore, quando si presenta un errore ti prego di effettuare nuovamente il login, fare un clean cache e ritestare.
