### ISSUE TITLE
Uc210  che innesta 203 - tipologia istanze

### ISSUE THREAD

**Issue by SaraGiordano334** [guildenstern70/uibm-test#9]
-	Se l’utente seleziona il ruolo “Richiedente” la tipologia di istanza “Deposito Incarico” non verrà visualizzata. 
![Screenshot 2024-11-19 160521](https://github.com/user-attachments/assets/c30ff12e-9f92-4bad-a642-637c8b6b7cbb)

- Tra la lista delle istanze va tolto " Rinnovo marchio"

**Comment by SaraGiordano334** [comment]
io lo vedo ancora nella lista come mai? devo aggiornare qualcosa?

**Comment by lungarella-raffaele** [comment]
Scusami il secondo punto deve ancora essere risolto, ma il primo dovrebbe essere risolto

**Comment by e-guerriero** [comment]
Risolto anche il secondo punto
